title: Aarya Chauhan
logo: "/prifile-photo.jpg"
description: >
  <br>
  Full Stack | Frontend Engineer
  <br>
  <a href="https://www.linkedin.com/in/aarya-chauhan/">
    <img src="https://www.edigitalagency.com.au/wp-content/uploads/Linkedin-logo-png.png" width="100">
  </a>
  <a href="mailto:aaryachauhan11@gmail.com">
    <img src = "https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white">
  </a>
remote_theme: pages-themes/minimal@v0.2.0
