title: Aarya Chauhan
logo: "/prifile-photo.jpg"
description: >
  <br>
  Full Stack | Frontend Engineer
  <br>
  <a href="https://www.linkedin.com/in/aarya-chauhan/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:aaryachauhan11@gmail.com">
    <img src = "https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white">
  </a>
remote_theme: pages-themes/time-machine@v0.2.0
